### ISSUE TITLE
Searching for peer starts immediately

### ISSUE THREAD

**Issue by killmasud** [TBS1996/ocean-chat#37]
Let the user initiate the first search when visiting the site. 

After 1st connection is disconnected (for whatever reason) and a user is still on the website, search can continue automatically. 

Also, there should be an option to stop searching completely. For example, you may want to change your scores (e.g. you share a computer with a friend and want to see who they connect with or w/e).

**Comment by TBS1996** [comment]
yeah I agree! 

the 'new peer' button should turn into a 'stop searching button'. and maybe the firs ttime theres no chat window just a big button that says 'start searching' or something?

**Comment by TBS1996** [comment]
fixed! #44
